### ISSUE TITLE
Add functions to upload assets into room and other "editing" operations

### ISSUE THREAD

**Issue by codeanticode** [rawnsley/HubsCloudUtil#3]
@rawnsley I have been playing around with this package and I'm wondering how far I can go with it :-)

The motivation for this enhancement request is the following: teaching programming inside hubs in such a way that one could modify the room itself from the code... people have tried doing this in VR environments for quite a while, see [this demo](https://cognitive3d.com/blog/programming-in-virtual-reality) from some years ago as an early example.

In my particular case, I have been using [Processing](https://processing.org/) for a remote course, and was able to create a [simple Processing library](https://github.com/codeanticode/hubs-connect) that uses HubsCloudUtil to login into a room as the first step. In other words, I just adapted one of the unit tests in HubsCloudUtil to run from Processing :-) So my question is what else could we do? For instance, would it be possible to load a 3D asset from the code and maybe even move it around the room?

The [HubsApiTest](https://github.com/rawnsley/HubsCloudUtil/blob/master/avn.portal/src/test/java/avn/portal/HubsApiTest.kt) hints at an API that would allow doing all these kinds of things, is this documented somewhere? 

Thank you!

**Comment by rawnsley** [comment]
@codeanticode that's a cool idea! This API really just imitates a user (usually the room owner), so in theory anything a user or admin can do, this API can do. However, this is a bit like saying you don't need a web browser if you have cURL :-)

The back end is [Mozilla Reticulum](https://github.com/mozilla/reticulum) and is open source, but the interface isn't documented and the code is a bit opaque if you don't speak Elixr (which I don't). That said, the room management functions are relatively simple and limited in scope so it shouldn't be too hard to puzzle out and extend this API for things like object upload and pinning.

The bulk of the traffic that passes through Reticulum is for the [NAF system](https://github.com/networked-aframe) and is mostly just forwarded on blindly by Reticulum from client to client. This definitely covers things like object movement and would be one of the key parts of a programming API. We have an in-house native Hubs client that does just this sort of thing.

When extending this API I've found it useful to sometimes puzzle things out by looking at the code, but often to just inspect the WebSocket traffic directly in the browser console: you can perform an action in Hubs and see what specific messages were sent.

If you are not already on the [Hubs Discord server](https://discordapp.com/invite/wHmY4nd) you should join as there are like-minded individuals who could help. Your project is certainly cutting edge though and I'm not aware of anyone else taking this kind of server-side "puppeteer" approach as far as you are suggesting.

**Comment by codeanticode** [comment]
@rawnsley Thanks for your comments! I have used the Hubs Discord server a few times before, people are very friendly and responsive there. I will post about this idea to see if folks are interested in participating or have suggestions :-)

**Comment by codeanticode** [comment]
@rawnsley I made some progress with programmatic access to Hubs. I can enter the room after opening the url (which puts the user in the lobby), as well as setting the avatar and display name. However, I have not managed to get the avatar to be visible, it's in the room but just not visible. I was inspecting the WebSocket traffic when entering a room through the web, and tried a couple of things with the library:

https://github.com/codeanticode/hubs-connect/blob/master/src/codeanticode/hubs/HubsConnect.java#L116

but did not figured it out yet. If you have any suggestions, just let me know. I'd like to create a simple demo video where at least the "puppet avatar" is visible to share on discord, to get people interested.

**Comment by rawnsley** [comment]
@codeanticode I'm not sure exactly, but I think you are close. I seem to remember doing a brute-force comparison of the WebSocket traffic to make sure my client was doing the same thing as the web clients. It's also possible that avatar presence relies on the existence of the WebRTC connection in some way; I remember it has a slightly complex relationship with the Phoenix channels, but I don't remember the details.

Without having read into your code very much: you will need to set the player position and possibly some other things to make sure somewhere you can see them (they may default to the origin, but I'm not sure).

My version of the line you linked to looks like this:

`hubPhxChannel?.push("events:entered", mapOf("entryDisplayType" to "ClassVR", "userAgent" to "Eduverse/2.0 (ClassVR)"))`

I'm not sure why I included those map parameters, but it's possible they are required.

I hope that's some useful information to keep you moving forward.

**Comment by codeanticode** [comment]
@rawnsley quick question, I noticed that the data map for the "naf" message that I construct manually to update the user avatar is missing the "networkId", "owner", "creator", and "lastOwnerTime" fields that I see in the messages sent by the web client. Where can I get those from?

**Comment by rawnsley** [comment]
@codeanticode The network ID is a unique and shared identifier for the object, so if it's part of the scene (like an audio source) then you have to use that one or other users won't know what you mean. If you are creating the object you can just make one up. Similarly owner and creator are the identities of people in the scene or sometimes people that have pinned objects previously.

Not sure about lastOwnerTime; I think it's used to resolve conflicts where two people claim to be the owners of the object and you want to know which to obey. The only time I set it in code I just grab the current system time, which might be wrong now I look at it, but it seems to work.

**Comment by codeanticode** [comment]
Thanks for the quick response! Yes, I figured I need those additional IDs. I will look at the code again later, but can I get then from HubsCloudUtil, or need to parse the WebSocket messages manually?

**Comment by rawnsley** [comment]
You can get them via HubsCloudUtil more or less I think. Worst case scenario is that you are interfacing at the Phoenix layer: you subscribe to channels and those channels issue events such as _naf_ or _pin_, which contain JSON encoded maps of properties.

**Comment by codeanticode** [comment]
Awesome, I will look into it!

**Comment by codeanticode** [comment]
Adding the session id to the naf messages was key to place visible avatars and other 3-D models. I think you could close this issue, since it seems like I'd be able to implement my own editing functions by sending the appropriate messages to Reticulum :-)
